# Generated by Django 5.0.7 on 2025-04-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_student_phone_number_student_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
