# Generated by Django 5.0.7 on 2025-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_attendance_status_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default='temp_username', max_length=50, unique=True),
        ),
    ]
